/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Lukas
 */
public class Cargando extends javax.swing.JPanel {

    /**
     * Creates new form Cargando
     */
    public Cargando() {
        initComponents();

        lbl_imagen.setSize(200, 200);
        ImageIcon imagen = new ImageIcon("C:/Users/Lukas/Downloads/2.gif");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lbl_imagen.getWidth(), lbl_imagen.getHeight(), Image.SCALE_DEFAULT));
        lbl_imagen.setIcon(icono);
        this.repaint();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_imagen = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        lbl_imagen.setMaximumSize(null);
        lbl_imagen.setMinimumSize(null);
        lbl_imagen.setPreferredSize(null);
        add(lbl_imagen);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_imagen;
    // End of variables declaration//GEN-END:variables
}
