/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Interface.Hoteleria.Parametros_Habitacion;
import Interface.Hoteleria.Parametros_Pileta;
import Interface.Hoteleria.Parametros_Salon;
import LN.Persona.Usuario.Usuario;
import LN.Varios.Hosteria;
import LN.Varios.Maestro;

/**
 *
 * @author Lukas
 */
public class Configuraciones extends javax.swing.JPanel {

private Hosteria unaHosteria;
    public Configuraciones(Hosteria unaHosteria) {
        this.unaHosteria = unaHosteria;
        initComponents();
        
         if (Acceso.getLogueado() != null) {
            if (Acceso.getLogueado() instanceof Maestro) {
                btn_opcionesHabitacion.setEnabled(true);
                btn_opcionesPileta.setEnabled(true);

            } else if (Acceso.getLogueado() instanceof Usuario) {
                Usuario unUsuario = (Usuario) Acceso.getLogueado();
                if (!unUsuario.getRol().getPermisos().containsKey("iop")) {
                    btn_opcionesPileta.setEnabled(false);
                } else {
                    btn_opcionesPileta.setEnabled(true);
                }
                if (!unUsuario.getRol().getPermisos().containsKey("ioh")) {
                    btn_opcionesHabitacion.setEnabled(false);
                } else {
                    btn_opcionesHabitacion.setEnabled(true);
                }
                if (!unUsuario.getRol().getPermisos().containsKey("ios")) {
                    btn_opcionesSalon.setEnabled(false);
                } else {
                    btn_opcionesSalon.setEnabled(true);
                }
        
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_opcionesHabitacion = new javax.swing.JButton();
        btn_opcionesPileta = new javax.swing.JButton();
        btn_opcionesSalon = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pnl_Cuerpo = new javax.swing.JPanel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Herramientas"));
        jPanel1.setLayout(new java.awt.GridLayout(6, 1));

        btn_opcionesHabitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PCI cards.png"))); // NOI18N
        btn_opcionesHabitacion.setText("<html><p>Opciones de</p><p>Habitación</p></html>");
        btn_opcionesHabitacion.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_opcionesHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_opcionesHabitacionActionPerformed(evt);
            }
        });
        jPanel1.add(btn_opcionesHabitacion);

        btn_opcionesPileta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/feet - copia.png"))); // NOI18N
        btn_opcionesPileta.setText("<html><p>Opciones</p><p>de Pileta</p></html>");
        btn_opcionesPileta.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_opcionesPileta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_opcionesPiletaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_opcionesPileta);

        btn_opcionesSalon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Moneda.png"))); // NOI18N
        btn_opcionesSalon.setText("<html><p>Opciones</p><p>del Salón</p></html>");
        btn_opcionesSalon.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_opcionesSalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_opcionesSalonActionPerformed(evt);
            }
        });
        jPanel1.add(btn_opcionesSalon);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ion Home folder.png"))); // NOI18N
        jButton1.setText("<html><p>Editar la</p><p>Entidad</p></html>");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        pnl_Cuerpo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnl_Cuerpo.setLayout(new javax.swing.BoxLayout(pnl_Cuerpo, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Cuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
            .addComponent(pnl_Cuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_opcionesHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_opcionesHabitacionActionPerformed
        Parametros_Habitacion losEstados = new Parametros_Habitacion(unaHosteria, null);
        pnl_Cuerpo.removeAll();
        pnl_Cuerpo.add(losEstados);
        pnl_Cuerpo.updateUI();
    }//GEN-LAST:event_btn_opcionesHabitacionActionPerformed

    private void btn_opcionesPiletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_opcionesPiletaActionPerformed
        Parametros_Pileta losParametros = new Parametros_Pileta(unaHosteria.getPileta());
        pnl_Cuerpo.removeAll();
        pnl_Cuerpo.add(losParametros);
        pnl_Cuerpo.updateUI();
    }//GEN-LAST:event_btn_opcionesPiletaActionPerformed

    private void btn_opcionesSalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_opcionesSalonActionPerformed
        Parametros_Salon parSal = new Parametros_Salon(unaHosteria);
        pnl_Cuerpo.removeAll();
        pnl_Cuerpo.add(parSal);
        pnl_Cuerpo.updateUI();
    }//GEN-LAST:event_btn_opcionesSalonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Vista_Empresa unaVista = new Vista_Empresa(unaHosteria);
        pnl_Cuerpo.removeAll();
        pnl_Cuerpo.add(unaVista);
        pnl_Cuerpo.updateUI();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_opcionesHabitacion;
    private javax.swing.JButton btn_opcionesPileta;
    private javax.swing.JButton btn_opcionesSalon;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnl_Cuerpo;
    // End of variables declaration//GEN-END:variables
}
