/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Hoteleria;

import Interface.Personas.ABM_Visitantes;
import Interface.Acceso;
import Interface.GUIM;
import Interface.Personas.Vista_Visitante;
import LN.Alquileres.Habitacion;
import LN.Alquileres.Hospedaje_Habitacion;
import LN.Alquileres.Reserva_Habitacion;
import LN.Alquileres.Tarifa_Habitacion;
import LN.Persona.Visitante.Afiliado;
import LN.Persona.Visitante.Visitante;
import LN.Varios.Hosteria;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;

/**
 *
 * @author Lukas
 */
public class Check_IN extends javax.swing.JPanel {

    private Hosteria unaHosteria;
    private JButton elBoton;
    private Visitante huesped;
    private JList unaLista;
    private Reserva_Habitacion seleccionada;

    public Check_IN(Hosteria unaHosteria, JButton elBoton) {
        this.unaHosteria = unaHosteria;
        this.elBoton = elBoton;
        initComponents();
        GUIM.decimalPositivo(txt_Descuento);
        timer.start();
        if (elBoton != null) {
            txt_1.setText(elBoton.getName());
        }
        Calendar calendario = Calendar.getInstance();
        dp_diaIN.setDate(calendario.getTime());
        calendario.add(Calendar.DAY_OF_MONTH, 1);
        dp_diaOUT.setDate(calendario.getTime());

        Integer habitacionBuscada = Integer.parseInt(elBoton.getName());
        if (GUIM.retornarHabitacion(habitacionBuscada, unaHosteria) != null) {
            Habitacion unaHabitacion = GUIM.retornarHabitacion(habitacionBuscada, unaHosteria);
        }
        for (Tarifa_Habitacion unTarifa : unaHosteria.getTarifas_Habitacion()) {
            cbx_Tarifas_Hab.addItem(unTarifa);
        }
        cbx_Tarifas_Hab.setSelectedIndex(0);
        txt_Precio_Unitario.setText(String.valueOf(((Tarifa_Habitacion) cbx_Tarifas_Hab.getSelectedItem()).getPrecio()));



        cbx_Tarifas_Hab.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent ie) {
                if (cbx_Tarifas_Hab.getSelectedIndex() != -1) {
                    Tarifa_Habitacion unaTarifa = (Tarifa_Habitacion) cbx_Tarifas_Hab.getSelectedItem();

                    switch (unaTarifa.getTipo()) {
                        case "Single":
                            txt_Precio_Unitario.setText(String.valueOf(unaTarifa.getPrecio()));
                        case "Doble Matrimonial":
                            txt_Precio_Unitario.setText(String.valueOf(unaTarifa.getPrecio()));
                        case "Doble Separada":
                            txt_Precio_Unitario.setText(String.valueOf(unaTarifa.getPrecio()));
                        case "Matrimonial + 1":
                            txt_Precio_Unitario.setText(String.valueOf(unaTarifa.getPrecio()));
                        case "Trible Separada":
                            txt_Precio_Unitario.setText(String.valueOf(unaTarifa.getPrecio()));
                        case "Matrimonial + 2":
                            txt_Precio_Unitario.setText(String.valueOf(unaTarifa.getPrecio()));
                        case "Cuadruble Separada":
                            txt_Precio_Unitario.setText(String.valueOf(unaTarifa.getPrecio()));
                        case "Sin Cargo":
                            txt_Precio_Unitario.setText(String.valueOf(unaTarifa.getPrecio()));

                    }
                }
            }
        });

        txt_Descuento.addCaretListener(new CaretListener() {
            @Override
            public void caretUpdate(CaretEvent ce) {
                calcularDescuento();
            }
        });

    }
    private Timer timer = new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent ae) {
            lbl_horaIN.setText(GUIM.getHoraActual());
            updateUI();
        }
    });

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Contenedor = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JTextField();
        pnl_Pestañas = new javax.swing.JTabbedPane();
        Pestaña_Habitacion = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_1 = new javax.swing.JTextField();
        btn_disponibles = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        dp_diaIN = new org.jdesktop.swingx.JXDatePicker();
        dp_diaOUT = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_horaIN = new javax.swing.JLabel();
        lbl_horaOUT = new javax.swing.JLabel();
        txt_Precio_Unitario = new javax.swing.JTextField();
        txt_Descuento = new javax.swing.JTextField();
        txt_Total = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbx_Tarifas_Hab = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_apellido_rep = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txt_nombre_rep = new javax.swing.JTextField();
        panelRect1 = new org.edisoncor.gui.panel.PanelRect();
        btn_Capturar_Visitante = new javax.swing.JButton();
        btn_listarCaja = new javax.swing.JButton();
        btn_Capturar_Reserva = new javax.swing.JButton();
        btn_Ingresar_Mov = new javax.swing.JButton();
        btn_nuevo_Visitante = new javax.swing.JButton();
        Pestaña_Huesped = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_Nombre_Vis = new javax.swing.JTextField();
        txt_apellido_vis = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_Email_Vis = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_ocupacion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_sexoVis = new javax.swing.JTextField();
        txt_EstadoCivil = new javax.swing.JTextField();
        txt_motivoVis = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        lbl_tipoDNI = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_CondAf_Vis = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_nro_carnet = new javax.swing.JTextField();
        txt_Documento_Vis = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_FechaNac_Vis = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_Pais_vis = new javax.swing.JTextField();
        txt_Porvincia_Vis = new javax.swing.JTextField();
        txt_Localidad_Vis = new javax.swing.JTextField();
        txt_Domicilio_Vis = new javax.swing.JTextField();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        Panel_Contenedor.setMaximumSize(null);
        Panel_Contenedor.setPreferredSize(new java.awt.Dimension(600, 493));

        lbl_titulo.setEditable(false);
        lbl_titulo.setBackground(new java.awt.Color(153, 153, 153));
        lbl_titulo.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setText("Check IN - Habitación");
        lbl_titulo.setFocusable(false);

        pnl_Pestañas.setRequestFocusEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Habitaciones a Alojar"));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        txt_1.setEditable(false);
        jPanel2.add(txt_1);

        btn_disponibles.setText("Otras Habitaciones Disponibles");
        btn_disponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_disponiblesActionPerformed(evt);
            }
        });
        jPanel2.add(btn_disponibles);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles de Alojamiento"));

        dp_diaIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dp_diaINActionPerformed(evt);
            }
        });

        dp_diaOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dp_diaOUTActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel1.setText("Fecha y Hora de Ingreso:");

        jLabel2.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel2.setText("Fecha y Hora de Egreso");

        lbl_horaIN.setBackground(new java.awt.Color(153, 204, 0));

        lbl_horaOUT.setText("12:00");
        lbl_horaOUT.setBackground(new java.awt.Color(153, 204, 0));

        txt_Precio_Unitario.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_Precio_UnitarioCaretUpdate(evt);
            }
        });

        txt_Descuento.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_DescuentoCaretUpdate(evt);
            }
        });
        txt_Descuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DescuentoActionPerformed(evt);
            }
        });
        txt_Descuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_DescuentoKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel3.setText("Precio Unitario:");

        jLabel4.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel4.setText("Descuento %:");

        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel5.setText("TOTAL:");

        jLabel6.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel6.setText("Tarifa");

        jLabel22.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel22.setText("Apellido del Representante:");

        jLabel23.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel23.setText("Nombre del Representante:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_Tarifas_Hab, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Precio_Unitario)
                    .addComponent(txt_Total)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(dp_diaIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_horaIN, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(dp_diaOUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_horaOUT))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Descuento, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_apellido_rep)
                    .addComponent(txt_nombre_rep)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txt_apellido_rep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txt_nombre_rep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Precio_Unitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbx_Tarifas_Hab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Descuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dp_diaOUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_horaOUT)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(dp_diaIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_horaIN, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        panelRect1.setBackground(new java.awt.Color(255, 255, 255));
        panelRect1.setForeground(new java.awt.Color(255, 255, 255));
        panelRect1.setColorPrimario(new java.awt.Color(255, 255, 255));
        panelRect1.setColorSecundario(new java.awt.Color(102, 102, 102));
        panelRect1.setPreferredSize(new java.awt.Dimension(150, 184));

        btn_Capturar_Visitante.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        btn_Capturar_Visitante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/REAL OSX SHERLOCK.png"))); // NOI18N
        btn_Capturar_Visitante.setText("<html><p>Capturar</p><p>Visitante</p></html>");
        btn_Capturar_Visitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Capturar_VisitanteActionPerformed(evt);
            }
        });

        btn_listarCaja.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        btn_listarCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Close.png"))); // NOI18N
        btn_listarCaja.setText("Cancelar");
        btn_listarCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listarCajaActionPerformed(evt);
            }
        });

        btn_Capturar_Reserva.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        btn_Capturar_Reserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Reservas.png"))); // NOI18N
        btn_Capturar_Reserva.setText("<html><p>Capturar</p><p>Reserva</p></html>");
        btn_Capturar_Reserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Capturar_ReservaActionPerformed(evt);
            }
        });

        btn_Ingresar_Mov.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        btn_Ingresar_Mov.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar_2.png"))); // NOI18N
        btn_Ingresar_Mov.setText("Aceptar");
        btn_Ingresar_Mov.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Ingresar_Mov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Ingresar_MovActionPerformed(evt);
            }
        });

        btn_nuevo_Visitante.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        btn_nuevo_Visitante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Add.png"))); // NOI18N
        btn_nuevo_Visitante.setText("<html><p>Nuevo</p><p>Visitante</p></html>");
        btn_nuevo_Visitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevo_VisitanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRect1Layout = new javax.swing.GroupLayout(panelRect1);
        panelRect1.setLayout(panelRect1Layout);
        panelRect1Layout.setHorizontalGroup(
            panelRect1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRect1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelRect1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_Ingresar_Mov, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_nuevo_Visitante, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Capturar_Reserva, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Capturar_Visitante, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_listarCaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        panelRect1Layout.setVerticalGroup(
            panelRect1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRect1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btn_Capturar_Visitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Capturar_Reserva, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_nuevo_Visitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Ingresar_Mov)
                .addGap(18, 18, 18)
                .addComponent(btn_listarCaja)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Pestaña_HabitacionLayout = new javax.swing.GroupLayout(Pestaña_Habitacion);
        Pestaña_Habitacion.setLayout(Pestaña_HabitacionLayout);
        Pestaña_HabitacionLayout.setHorizontalGroup(
            Pestaña_HabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pestaña_HabitacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pestaña_HabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRect1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Pestaña_HabitacionLayout.setVerticalGroup(
            Pestaña_HabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pestaña_HabitacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pestaña_HabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRect1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                    .addGroup(Pestaña_HabitacionLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pnl_Pestañas.addTab("Alojamiento", Pestaña_Habitacion);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales"));
        jPanel4.setPreferredSize(new java.awt.Dimension(615, 238));

        jLabel7.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel7.setText("Nombre:");

        jLabel8.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel8.setText("Apellido:");

        jLabel9.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel9.setText("Sexo:");

        txt_Nombre_Vis.setEditable(false);
        txt_Nombre_Vis.setFocusable(false);

        txt_apellido_vis.setEditable(false);
        txt_apellido_vis.setFocusable(false);

        jLabel10.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel10.setText("Telefono:");

        txt_telefono.setEditable(false);
        txt_telefono.setFocusable(false);

        jLabel12.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel12.setText("E-mail:");

        txt_Email_Vis.setEditable(false);
        txt_Email_Vis.setFocusable(false);

        jLabel18.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel18.setText("Ocupacion:");

        txt_ocupacion.setEditable(false);
        txt_ocupacion.setFocusable(false);

        jLabel11.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel11.setText("Estado Civil:");

        jLabel15.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel15.setText("Motivo de Visita:");

        txt_sexoVis.setEditable(false);
        txt_sexoVis.setFocusable(false);

        txt_EstadoCivil.setEditable(false);
        txt_EstadoCivil.setFocusable(false);

        txt_motivoVis.setEditable(false);
        txt_motivoVis.setFocusable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_Email_Vis, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Nombre_Vis))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ocupacion))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_telefono)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_motivoVis))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_apellido_vis, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_EstadoCivil)
                            .addComponent(txt_sexoVis)))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_Nombre_Vis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txt_apellido_vis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txt_ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txt_motivoVis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txt_EstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_Email_Vis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txt_sexoVis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Documentación"));

        lbl_tipoDNI.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        lbl_tipoDNI.setText("Identificacion:");

        jLabel14.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel14.setText("Condicion de Afiliacion:");

        txt_CondAf_Vis.setEditable(false);
        txt_CondAf_Vis.setFocusable(false);

        jLabel17.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel17.setText("Nro. de Carnet:");

        txt_nro_carnet.setEditable(false);
        txt_nro_carnet.setFocusable(false);

        txt_Documento_Vis.setEditable(false);
        txt_Documento_Vis.setFocusable(false);

        jLabel13.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel13.setText("Fecha de Nacimiento:");

        txt_FechaNac_Vis.setEditable(false);
        txt_FechaNac_Vis.setFocusable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(lbl_tipoDNI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Documento_Vis))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_CondAf_Vis, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_FechaNac_Vis))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nro_carnet)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_CondAf_Vis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txt_nro_carnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_tipoDNI)
                        .addComponent(txt_Documento_Vis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txt_FechaNac_Vis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Procedencia"));

        jLabel16.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel16.setText("Domicilio:");

        jLabel19.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel19.setText("País:");

        jLabel20.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel20.setText("Provincia:");

        jLabel21.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel21.setText("Localidad");

        txt_Pais_vis.setEditable(false);
        txt_Pais_vis.setFocusable(false);

        txt_Porvincia_Vis.setEditable(false);
        txt_Porvincia_Vis.setFocusable(false);

        txt_Localidad_Vis.setEditable(false);
        txt_Localidad_Vis.setFocusable(false);

        txt_Domicilio_Vis.setEditable(false);
        txt_Domicilio_Vis.setFocusable(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Pais_vis, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Localidad_Vis)))
                .addGap(42, 42, 42)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Porvincia_Vis, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(txt_Domicilio_Vis))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txt_Pais_vis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txt_Porvincia_Vis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txt_Localidad_Vis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txt_Domicilio_Vis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Pestaña_HuespedLayout = new javax.swing.GroupLayout(Pestaña_Huesped);
        Pestaña_Huesped.setLayout(Pestaña_HuespedLayout);
        Pestaña_HuespedLayout.setHorizontalGroup(
            Pestaña_HuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pestaña_HuespedLayout.createSequentialGroup()
                .addGroup(Pestaña_HuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE))
                .addContainerGap())
        );
        Pestaña_HuespedLayout.setVerticalGroup(
            Pestaña_HuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pestaña_HuespedLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_Pestañas.addTab("Datos Personales", Pestaña_Huesped);
        Pestaña_Huesped.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout Panel_ContenedorLayout = new javax.swing.GroupLayout(Panel_Contenedor);
        Panel_Contenedor.setLayout(Panel_ContenedorLayout);
        Panel_ContenedorLayout.setHorizontalGroup(
            Panel_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Pestañas)
            .addComponent(lbl_titulo)
        );
        Panel_ContenedorLayout.setVerticalGroup(
            Panel_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ContenedorLayout.createSequentialGroup()
                .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Pestañas)
                .addContainerGap())
        );

        add(Panel_Contenedor);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Capturar_VisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Capturar_VisitanteActionPerformed
        JDialog frame;
        if (SwingUtilities.getWindowAncestor(this) instanceof JDialog) {
            frame = new JDialog((JDialog) SwingUtilities.getWindowAncestor(this), true);
        } else {
            frame = new JDialog((JFrame) SwingUtilities.getWindowAncestor(this), true);
        }
        Vista_Visitante panel_captura_visitante = new Vista_Visitante(unaHosteria, huesped);
        frame.getContentPane().removeAll();
        frame.getContentPane().add(panel_captura_visitante);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.show();

        if (panel_captura_visitante.getSelected_Visitante().getSelectedRowCount() != 0) {
            Visitante unVisitante = (Visitante) panel_captura_visitante.getSelected_Visitante().getValueAt(panel_captura_visitante.getSelected_Visitante().getSelectedRow(), 0);
            huesped = unVisitante;
            txt_apellido_rep.setText(unVisitante.getApellido());
            txt_nombre_rep.setText(unVisitante.getNombre());
            txt_apellido_vis.setText(unVisitante.getApellido());
            txt_Nombre_Vis.setText(unVisitante.getNombre());
            txt_ocupacion.setText(unVisitante.getOcupacion());
            txt_motivoVis.setText(unVisitante.getMotivo_visita());
            txt_telefono.setText(unVisitante.getTelefono());
            txt_EstadoCivil.setText(unVisitante.getEstado_civil().toString());
            txt_Email_Vis.setText(unVisitante.getE_mail());
            txt_sexoVis.setText(unVisitante.getSexo().toString());
            txt_Pais_vis.setText(unVisitante.getDireccion().getPais().toString());
            txt_Porvincia_Vis.setText(unVisitante.getDireccion().getProvincia().toString());
            txt_Localidad_Vis.setText(unVisitante.getDireccion().getLocalidad().toString());
            txt_Domicilio_Vis.setText(unVisitante.getDireccion().getDomicilio());
            txt_CondAf_Vis.setText(unVisitante.getCondicion_af());
            txt_Documento_Vis.setText(unVisitante.getDni());
            if (unVisitante.getFnac() != null) {
                txt_FechaNac_Vis.setText(new SimpleDateFormat("dd/MM/yyyy").format(unVisitante.getFnac()));
            } else {
                txt_FechaNac_Vis.setText("Sin Detalle");
            }
            if (unVisitante instanceof Afiliado) {
                txt_nro_carnet.setText(((Afiliado) unVisitante).getNumero_carnet());
            } else {
                txt_nro_carnet.setText("No posee dicho Número");
            }

        }

    }//GEN-LAST:event_btn_Capturar_VisitanteActionPerformed

    private void btn_Ingresar_MovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Ingresar_MovActionPerformed
        Habitacion laHabitacion = null;
        for (Habitacion unaHabitacion : unaHosteria.getHabitaciones()) {
            if (unaHabitacion.getNumero() == (Integer.parseInt(txt_1.getText()))) {
                laHabitacion = unaHabitacion;
            }
        }
        Date fecha_entrada = dp_diaIN.getDate();
        Date fecha_salida = dp_diaOUT.getDate();
        Tarifa_Habitacion unaTarifa = (Tarifa_Habitacion) cbx_Tarifas_Hab.getSelectedItem();
        double unDescuento = 0.00;
        if (!txt_Descuento.getText().isEmpty()) {
                unDescuento = Double.valueOf(txt_Descuento.getText());
        }
        int cantidadDias = GUIM.diferenciasDeFechas(fecha_entrada, fecha_salida);
        Double aPagar = Double.parseDouble(txt_Total.getText()) * GUIM.diferenciasDeFechas(fecha_entrada, fecha_salida);
        try {
            Hospedaje_Habitacion unHospedaje = unaHosteria.CheckIN_Habitacion(laHabitacion, huesped, unaTarifa, fecha_entrada, fecha_salida, unDescuento);

            unaHosteria.crearAuditoria("ADD", "Agrego un Hospedaje a nombre de : " + huesped.getApellido() + " " + huesped.getNombre() + ", Habitacion " + laHabitacion.getNumero() + ", tipo " + unaTarifa.getTipo(), Acceso.getUsuario(), GUIM.getHoraActual());

            unaHosteria.altaMovimiento_Hospedaje(aPagar, unaTarifa.getTipo(), unHospedaje.getIngreso(), unHospedaje, GUIM.getHoraActual());

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        SwingUtilities.getWindowAncestor(this).dispose();

    }//GEN-LAST:event_btn_Ingresar_MovActionPerformed

    private void calcularDescuento() {
        if (!txt_Precio_Unitario.getText().isEmpty()) {
            Double precioUnitario = Double.parseDouble(txt_Precio_Unitario.getText());
            if (txt_Descuento.getText().isEmpty()) {
                txt_Total.setText(String.valueOf(precioUnitario));
            } else {
                Double descuentoUnitario = Double.parseDouble(txt_Descuento.getText());
                Double totalPrecio = precioUnitario - ((descuentoUnitario * precioUnitario) / 100);
                txt_Total.setText(String.valueOf(totalPrecio));
            }
        }
    }

    private void txt_Precio_UnitarioCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_Precio_UnitarioCaretUpdate
        calcularDescuento();
    }//GEN-LAST:event_txt_Precio_UnitarioCaretUpdate

    private void btn_nuevo_VisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevo_VisitanteActionPerformed

        JDialog jf;
        if (SwingUtilities.getWindowAncestor(this) instanceof JDialog) {
            jf = new JDialog((JDialog) SwingUtilities.getWindowAncestor(this), true);
        } else {
            jf = new JDialog((JFrame) SwingUtilities.getWindowAncestor(this), true);
        }

        ABM_Visitantes gestorVisitante = new ABM_Visitantes(unaHosteria);
        jf.getContentPane().removeAll();
        jf.getContentPane().add(gestorVisitante);
        jf.pack();
        jf.setLocationRelativeTo(null);
        jf.show();



        Visitante unVisitante = (Visitante) unaHosteria.getVisitantes().get(unaHosteria.getVisitantes().size() - 1);
        huesped = unVisitante;
        txt_apellido_rep.setText(unVisitante.getApellido() + " " + unVisitante.getNombre());
        txt_apellido_vis.setText(unVisitante.getApellido());
        txt_Nombre_Vis.setText(unVisitante.getNombre());
        txt_ocupacion.setText(unVisitante.getOcupacion());
        txt_motivoVis.setText(unVisitante.getMotivo_visita());
        txt_telefono.setText(unVisitante.getTelefono());
        txt_EstadoCivil.setText(unVisitante.getEstado_civil().toString());
        txt_Email_Vis.setText(unVisitante.getE_mail());
        txt_sexoVis.setText(unVisitante.getSexo().toString());
        txt_Pais_vis.setText(unVisitante.getDireccion().getPais().toString());
        txt_Porvincia_Vis.setText(unVisitante.getDireccion().getProvincia().toString());
        txt_Localidad_Vis.setText(unVisitante.getDireccion().getLocalidad().toString());
        txt_Domicilio_Vis.setText(unVisitante.getDireccion().getDomicilio());
        txt_CondAf_Vis.setText(unVisitante.getCondicion_af());
        txt_Documento_Vis.setText(unVisitante.getDni());
        if (unVisitante.getFnac() != null) {
            txt_FechaNac_Vis.setText(new SimpleDateFormat("dd/MM/yyyy").format(unVisitante.getFnac()));
        } else {
            txt_FechaNac_Vis.setText("Sin Detalle");
        }

        if (unVisitante instanceof Afiliado) {
            txt_nro_carnet.setText(((Afiliado) unVisitante).getNumero_carnet());
        } else {
            txt_nro_carnet.setText("No posee dicho Número");
        }


        this.updateUI();
    }//GEN-LAST:event_btn_nuevo_VisitanteActionPerformed

    private void btn_disponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_disponiblesActionPerformed
        JDialog jf;
        if (SwingUtilities.getWindowAncestor(this) instanceof JDialog) {
            jf = new JDialog((JDialog) SwingUtilities.getWindowAncestor(this), true);
        } else {
            jf = new JDialog((JFrame) SwingUtilities.getWindowAncestor(this), true);
        }
        List<Habitacion> disponibles = unaHosteria.getHabitaciones();
        Habitaciones_Disponibles habitaciones = new Habitaciones_Disponibles(disponibles);
        jf.getContentPane().removeAll();
        jf.getContentPane().add(habitaciones);
        jf.pack();
        jf.setLocationRelativeTo(null);
        jf.show();

        if (habitaciones.getHabitacion_Deleccionada() != null) {
            String numero = String.valueOf(((Habitacion) habitaciones.getHabitacion_Deleccionada().getSelectedValue()).getNumero());
            txt_1.setText(numero);
        }

    }//GEN-LAST:event_btn_disponiblesActionPerformed

    private void txt_DescuentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DescuentoKeyTyped
        if (!GUIM.esEntero(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_DescuentoKeyTyped

    private void dp_diaOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dp_diaOUTActionPerformed
        if (dp_diaOUT.getDate().before(dp_diaIN.getDate()) || dp_diaOUT.getDate().equals(dp_diaIN.getDate())) {
            JOptionPane.showMessageDialog(this, "La Fecha de Salida no puede ser anterior o igual a la Fecha de Entrada");
            Calendar calendario = Calendar.getInstance();
            calendario.setTime(dp_diaIN.getDate());
            calendario.add(Calendar.DAY_OF_MONTH, 1);
            dp_diaOUT.setDate(calendario.getTime());
        }

    }//GEN-LAST:event_dp_diaOUTActionPerformed

    private void btn_listarCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listarCajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_listarCajaActionPerformed

    private void btn_Capturar_ReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Capturar_ReservaActionPerformed
        Calendar hoy = Calendar.getInstance();
        Calendar diaReserva = Calendar.getInstance();

        List<Reserva_Habitacion> Lista_del_dia = new LinkedList<>();
        for (Reserva_Habitacion unaReserva_Habitacion : unaHosteria.getReservas()) {
            diaReserva.setTime(unaReserva_Habitacion.getDesdeFecha());
            if (diaReserva.get(Calendar.DAY_OF_YEAR) == hoy.get(Calendar.DAY_OF_YEAR)) {
                if (String.valueOf(unaReserva_Habitacion.getDeHabitacion().getNumero()).equals(txt_1.getText())) {
                    Lista_del_dia.add(unaReserva_Habitacion);
                }
            }
        }

        if (!Lista_del_dia.isEmpty()) {
            JDialog frame;
            if (SwingUtilities.getWindowAncestor(this) instanceof JDialog) {
                frame = new JDialog((JDialog) SwingUtilities.getWindowAncestor(this), true);
            } else {
                frame = new JDialog((JFrame) SwingUtilities.getWindowAncestor(this), true);
            }
            Capturar_RH unaL = new Capturar_RH(Lista_del_dia);
            frame.getContentPane().removeAll();
            frame.getContentPane().add(unaL);
            frame.pack();
            frame.setLocationRelativeTo(null);
            frame.show();

            if (unaL.getUnaReserva_Habitacion() != null) {
                seleccionada = unaL.getUnaReserva_Habitacion();
                dp_diaIN.setDate(seleccionada.getDesdeFecha());
                dp_diaOUT.setDate(seleccionada.getHastaFecha());
                cbx_Tarifas_Hab.setSelectedItem(seleccionada.getTipo());
                txt_Precio_Unitario.setText(String.valueOf(seleccionada.getTipo().getPrecio()));
                txt_Total.setText(String.valueOf(seleccionada.getTipo().getPrecio() * seleccionada.getCantidad_de_Noches()));
                txt_apellido_rep.setText(seleccionada.getApeVis());
                txt_nombre_rep.setText(seleccionada.getNombVis());
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existen reservas de esta Habitación para el dia de la fecha");
        }
    }//GEN-LAST:event_btn_Capturar_ReservaActionPerformed

    private void dp_diaINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dp_diaINActionPerformed
        Calendar elPuesto = Calendar.getInstance();
        elPuesto.setTime(dp_diaIN.getDate());
        elPuesto.add(Calendar.DAY_OF_YEAR, 1);
        dp_diaOUT.setDate(elPuesto.getTime());
    }//GEN-LAST:event_dp_diaINActionPerformed

    private void txt_DescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DescuentoActionPerformed

    private void txt_DescuentoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_DescuentoCaretUpdate
        if (!txt_Descuento.getText().isEmpty()) {
            if (Double.parseDouble(txt_Descuento.getText()) > 100) {
                JOptionPane.showMessageDialog(this, "No puede ingresar un valor mayor al 100 %");
                txt_Descuento.setText("0.00");
            }
        }
    }//GEN-LAST:event_txt_DescuentoCaretUpdate
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Contenedor;
    private javax.swing.JPanel Pestaña_Habitacion;
    private javax.swing.JPanel Pestaña_Huesped;
    private javax.swing.JButton btn_Capturar_Reserva;
    private javax.swing.JButton btn_Capturar_Visitante;
    private javax.swing.JButton btn_Ingresar_Mov;
    private javax.swing.JButton btn_disponibles;
    private javax.swing.JButton btn_listarCaja;
    private javax.swing.JButton btn_nuevo_Visitante;
    private javax.swing.JComboBox cbx_Tarifas_Hab;
    private org.jdesktop.swingx.JXDatePicker dp_diaIN;
    private org.jdesktop.swingx.JXDatePicker dp_diaOUT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbl_horaIN;
    private javax.swing.JLabel lbl_horaOUT;
    private javax.swing.JLabel lbl_tipoDNI;
    private javax.swing.JTextField lbl_titulo;
    private org.edisoncor.gui.panel.PanelRect panelRect1;
    private javax.swing.JTabbedPane pnl_Pestañas;
    private javax.swing.JTextField txt_1;
    private javax.swing.JTextField txt_CondAf_Vis;
    private javax.swing.JTextField txt_Descuento;
    private javax.swing.JTextField txt_Documento_Vis;
    private javax.swing.JTextField txt_Domicilio_Vis;
    private javax.swing.JTextField txt_Email_Vis;
    private javax.swing.JTextField txt_EstadoCivil;
    private javax.swing.JTextField txt_FechaNac_Vis;
    private javax.swing.JTextField txt_Localidad_Vis;
    private javax.swing.JTextField txt_Nombre_Vis;
    private javax.swing.JTextField txt_Pais_vis;
    private javax.swing.JTextField txt_Porvincia_Vis;
    private javax.swing.JTextField txt_Precio_Unitario;
    private javax.swing.JTextField txt_Total;
    private javax.swing.JTextField txt_apellido_rep;
    private javax.swing.JTextField txt_apellido_vis;
    private javax.swing.JTextField txt_motivoVis;
    private javax.swing.JTextField txt_nombre_rep;
    private javax.swing.JTextField txt_nro_carnet;
    private javax.swing.JTextField txt_ocupacion;
    private javax.swing.JTextField txt_sexoVis;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
